"""empty message

Revision ID: 962e143767b0
Revises: df0a8f18baf3
Create Date: 2019-03-04 19:50:43.018772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '962e143767b0'
down_revision = 'df0a8f18baf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('password', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'password')
    # ### end Alembic commands ###
